name: Update Game Database
on:
  push:
    branches: [ main ]
    paths:
      - 'g*/**'

# --- ADD THIS SECTION ---
permissions:
  contents: write
# ------------------------

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # Updated to v4 to avoid the Node.js warning
      - name: Set up Python
        uses: actions/setup-python@v5 # Updated to v5
        with:
          python-version: '3.x'
      - name: Run Scanner
        run: python scanner.py
      - name: Commit Database
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add database.json
          git diff-index --quiet HEAD || git commit -m "Update database.json"
          git push